# This is a basic workflow to help you get started with Actions

name: QUnit

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Node modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-
          
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: | 
          npm install pm2
          npm install
          
      # Runs a single command using the runners shell
      - name: Prepare Task
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REGION: ${{ secrets.REGION }}
          BUCKET: ${{ secrets.BUCKET }}
          UIN: ${{ secrets.UIN }}  
        run: |
          sed -i -e "s/10001/$UIN/" test/test.js
          sed -i -e "s/allowPrefix: '_ALLOW_DIR_\/\*'/allowPrefix: '\*'/" server/sts.js
          sed -i -e "s/process.env.SecretId/\"$SECRET_ID\"/" server/sts.js
          sed -i -e "s/process.env.SecretKey/\"$SECRET_KEY\"/" server/sts.js
          sed -i -e "s/process.env.Bucket/\"$BUCKET\"/" server/sts.js
          sed -i -e "s/process.env.Region/\"$REGION\"/" server/sts.js
          sed -i -e "s/PutObject/\*/" server/sts.js
      
      # Runs a set of commands using the runners shell
      - name: Start Server
        run: ./node_modules/pm2/bin/pm2 start server/sts.js

      - name: Test
        run: |
          node test/watcher.js

      - name: End Server
        run: ./node_modules/pm2/bin/pm2 stop server/sts.js
